spring.application.name=order-service

server.servlet.context-path=/orders
server.port=9020
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=Tushar@72003

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.inti.data-locations=classpath:data.sql